#!/usr/bin/env bash

if [ -z "$(type -p podman)" ]; then
	sudo apt update
	sudo apt install podman
fi

CONTAINER="cube-tools-qb"

STATUS="$(podman inspect --format '{{.State.Status}}' $CONTAINER 2>/dev/null)"

case $STATUS in
	exited|created)
		echo -n "Starting..."
		podman start $CONTAINER
		;& # ;& means fall-through
	running)
		echo "Attaching to running container. Press <enter> for new prompt."
		podman attach $CONTAINER
		;;
	*)
		podman run -it --name $CONTAINER cube-tools bash
		;;
esac
